#!/bin/sh
set -eu

# install-codex.sh — install codex-reflector into Codex's native hook system.
#
# POSIX sh, set -eu, python3 for the read-modify-write (no jq dependency),
# absolute physical paths, idempotent. It:
#   1. Generates a small WRAPPER script (codex-reflector-hook.sh) that exports
#      REFLECTOR_HOST=codex and execs python3 on the reflector. The wrapper makes
#      env-setting independent of Codex's hook-command execution model (whether or
#      not it shell-interprets the `command` string), and it stabilizes the exact
#      command string that the trust hash is computed over.
#   2. Merges PostToolUse/Stop/PreCompact wiring into ~/.codex/hooks.json (or
#      <project>/.codex/hooks.json), idempotently (dedup by our command).
#   3. PRE-TRUSTS the hook commands BY HASH (KTD-8/M5, primary path): writes
#      [hooks.state."<hooks.json>:<event>:<g>:<h>"] trusted_hash entries into
#      ~/.codex/config.toml, with a backup + parse-validation + rollback so the
#      user's live config is never corrupted.
#
# OPT-IN pre-edit hard-block (--preedit): additionally wires the PreToolUse entry
# (which lives in the SEPARATE hooks/codex-hooks-preedit.json fragment, deliberately
# NOT in the default codex-hooks.json — fix M-A: a PreToolUse hook forks python3 on
# every matched edit, so it is never wired by default).
#
# TRUST CAVEAT (honest): Codex's hook-definition canonicalization (what exactly it
# hashes) is internal and undocumented; no reproducible (definition -> hash)
# preimage was available to verify the algorithm. The trusted_hash this script
# writes is therefore BEST-EFFORT. A wrong/absent hash FAILS SAFE — Codex flags
# the hook as new/changed and SKIPS it until you trust it. If a hook is still
# flagged after install, complete a one-time interactive `/hooks` review in Codex
# (records the authoritative hash). FOOTNOTE FALLBACK ONLY: for one-off automation
# that vets hook sources out-of-band, `codex exec --dangerously-bypass-hook-trust`
# runs enabled hooks without persisted trust for that invocation (not recommended
# as a standing configuration).

usage() {
  printf '%s\n' "Usage: $0 [--force] [--preedit] [target-project-dir]"
  printf '%s\n' ""
  printf '%s\n' "Installs codex-reflector into Codex's native hook system."
  printf '%s\n' "Without target-project-dir, writes to ~/.codex/ (CODEX_HOME-aware)."
  printf '%s\n' "With target-project-dir, writes to target-project-dir/.codex/."
  printf '%s\n' ""
  printf '%s\n' "  --force     Replace an existing hooks.json instead of merging."
  printf '%s\n' "  --preedit   ALSO wire the OPT-IN pre-edit PreToolUse hard-block"
  printf '%s\n' "              (forks python3 per matched edit; off by default)."
}

force=0
preedit=0
target_root=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --force)
      force=1
      shift
      ;;
    --preedit)
      preedit=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      printf '%s\n' "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
    *)
      if [ "$target_root" != "" ]; then
        printf '%s\n' "Only one target-project-dir may be provided." >&2
        usage >&2
        exit 2
      fi
      target_root=$1
      shift
      ;;
  esac
done

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
plugin_root=$(dirname -- "$script_dir")
reflector_script="${plugin_root}/scripts/codex-reflector.py"

if [ ! -f "$reflector_script" ]; then
  printf '%s\n' "Cannot find codex-reflector.py at: $reflector_script" >&2
  exit 1
fi

# Resolve the Codex config dir to an ABSOLUTE PHYSICAL path. A relative target
# would otherwise leak the caller's cwd into the hook command and the trust-state
# key (which embeds the hooks.json absolute path Codex computes at runtime).
if [ "$target_root" != "" ]; then
  if [ ! -d "$target_root" ]; then
    mkdir -p "$target_root"
  fi
  target_abs=$(CDPATH='' cd -- "$target_root" && pwd -P)
  codex_dir="${target_abs}/.codex"
else
  codex_dir="${CODEX_HOME:-${HOME}/.codex}"
fi

mkdir -p "$codex_dir"
codex_dir=$(CDPATH='' cd -- "$codex_dir" && pwd -P)

hooks_path="${codex_dir}/hooks.json"
config_path="${codex_dir}/config.toml"
wrapper_path="${codex_dir}/codex-reflector-hook.sh"
preedit_wrapper_path="${codex_dir}/codex-reflector-preedit-hook.sh"

# 1. Generate the wrapper(s). Env-setting lives here, not in the hook command, so
#    it does not depend on Codex shell-interpreting the command string.
cat > "$wrapper_path" <<WRAP
#!/bin/sh
# Auto-generated by install-codex.sh. Sets the Codex host then runs the reflector.
export REFLECTOR_HOST=codex
exec python3 "${reflector_script}" "\$@"
WRAP
chmod +x "$wrapper_path"
printf '%s\n' "Wrote hook wrapper: $wrapper_path"

if [ "$preedit" -eq 1 ]; then
  cat > "$preedit_wrapper_path" <<WRAP
#!/bin/sh
# Auto-generated by install-codex.sh (--preedit). Enables the pre-edit hard-block.
export REFLECTOR_HOST=codex
export REFLECTOR_PREEDIT_BLOCK=1
exec python3 "${reflector_script}" "\$@"
WRAP
  chmod +x "$preedit_wrapper_path"
  printf '%s\n' "Wrote pre-edit hook wrapper: $preedit_wrapper_path"
fi

# Command strings the hooks will run (absolute wrapper paths).
hook_command="sh \"${wrapper_path}\""
preedit_command="sh \"${preedit_wrapper_path}\""

# 2. + 3. Merge hooks.json and pre-trust by hash — both in one python3 block
#    (python3 is already a hard dependency; no jq needed). The merge is idempotent
#    (dedups our command), and the config.toml write is backed up + parse-validated.
python3 - \
  "$hooks_path" "$config_path" "$hook_command" "$preedit_command" \
  "$preedit" "$force" <<'PY'
import hashlib
import json
import os
import sys

(
    hooks_path,
    config_path,
    hook_command,
    preedit_command,
    preedit_s,
    force_s,
) = sys.argv[1:7]
preedit = preedit_s == "1"
force = force_s == "1"
ours = {hook_command, preedit_command}

# --- Build the desired hook groups (default events + optional PreToolUse) ---
desired = {
    "PostToolUse": [
        {"hooks": [{"type": "command", "command": hook_command, "timeout": 360,
                    "statusMessage": "Codex reflector: reviewing tool output"}]}
    ],
    "Stop": [
        {"hooks": [{"type": "command", "command": hook_command, "timeout": 240,
                    "statusMessage": "Codex reflector: stop-time review"}]}
    ],
    "PreCompact": [
        {"matcher": "manual|auto",
         "hooks": [{"type": "command", "command": hook_command, "timeout": 240,
                    "statusMessage": "Codex reflector: pre-compaction summary"}]}
    ],
}
if preedit:
    desired["PreToolUse"] = [
        {"matcher": "Write|Edit|MultiEdit|Patch|NotebookEdit|apply_patch",
         "hooks": [{"type": "command", "command": preedit_command, "timeout": 60,
                    "statusMessage": "Codex reflector: pre-edit review (opt-in)"}]}
    ]

# --- Merge into existing hooks.json (idempotent: strip OUR prior commands) ---
existing = {}
if os.path.exists(hooks_path) and not force:
    try:
        existing = json.loads(open(hooks_path, encoding="utf-8").read()) or {}
    except (OSError, json.JSONDecodeError) as exc:
        print(f"  WARN: cannot parse {hooks_path} ({exc}); rerun with --force.", file=sys.stderr)
        sys.exit(1)
    if not isinstance(existing, dict):
        existing = {}

merged_hooks = dict(existing.get("hooks") or {})
for event in set(merged_hooks) | set(desired):
    prior = merged_hooks.get(event, []) or []
    # Drop any group whose every hook is one of OUR commands (clean re-install).
    kept = []
    for group in prior:
        if not isinstance(group, dict):
            kept.append(group)
            continue
        inner = [h for h in (group.get("hooks") or [])
                 if (h.get("command") if isinstance(h, dict) else None) not in ours]
        if inner:
            kept.append({**group, "hooks": inner})
        elif not group.get("hooks"):
            kept.append(group)
    merged_hooks[event] = kept + desired.get(event, [])
    if not merged_hooks[event]:
        del merged_hooks[event]

result = dict(existing)
result["hooks"] = merged_hooks
with open(hooks_path, "w", encoding="utf-8") as fh:
    fh.write(json.dumps(result, indent=2) + "\n")
print(f"  {'Installed' if not existing else 'Merged'} codex-reflector hooks -> {hooks_path}")

# --- Pre-trust by hash (KTD-8/M5): write [hooks.state] tables to config.toml ---
# State-key event names are snake_case (observed in real config.toml).
EVENT_KEY = {
    "PostToolUse": "post_tool_use",
    "Stop": "stop",
    "PreCompact": "pre_compact",
    "PreToolUse": "pre_tool_use",
}

entries = {}
for event, groups in (result.get("hooks") or {}).items():
    ev = EVENT_KEY.get(event)
    if ev is None:
        continue
    for gi, group in enumerate(groups or []):
        if not isinstance(group, dict):
            continue
        for hi, hook in enumerate(group.get("hooks") or []):
            if not isinstance(hook, dict) or hook.get("command") not in ours:
                continue  # only pre-trust OUR hooks
            payload = json.dumps(hook, sort_keys=True, separators=(",", ":"))
            digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
            entries[f"{hooks_path}:{ev}:{gi}:{hi}"] = f"sha256:{digest}"

if not entries:
    sys.exit(0)

cfg = ""
if os.path.exists(config_path):
    try:
        cfg = open(config_path, encoding="utf-8").read()
    except OSError as exc:
        print(f"  WARN: cannot read {config_path}: {exc}", file=sys.stderr)
        sys.exit(0)
    try:
        with open(config_path + ".codex-reflector.bak", "w", encoding="utf-8") as fh:
            fh.write(cfg)
    except OSError:
        pass


def toml_key(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


# Idempotent: drop any prior [hooks.state."<our key>"] table, then append fresh.
drop = {f"[hooks.state.{toml_key(k)}]" for k in entries}
out = []
skipping = False
for line in cfg.splitlines():
    stripped = line.strip()
    if stripped.startswith("[hooks.state."):
        skipping = stripped in drop
    elif stripped.startswith("["):
        skipping = False
    if not skipping:
        out.append(line)

while out and out[-1].strip() == "":
    out.pop()
new_text = "\n".join(out)
if new_text:
    new_text += "\n"
for key, val in entries.items():
    new_text += f"\n[hooks.state.{toml_key(key)}]\n"
    new_text += f'trusted_hash = "{val}"\n'

# Validate the result still parses before committing (rollback on failure).
try:
    import tomllib
    tomllib.loads(new_text)
except ModuleNotFoundError:
    pass  # py<3.11: skip validation; the text edit is conservative
except Exception as exc:  # noqa: BLE001 — any parse error must roll back
    print(f"  WARN: trust write would corrupt {config_path} ({exc}); skipped.", file=sys.stderr)
    print("  Run a one-time `/hooks` review in Codex to trust the hooks.", file=sys.stderr)
    sys.exit(0)

try:
    with open(config_path, "w", encoding="utf-8") as fh:
        fh.write(new_text)
except OSError as exc:
    print(f"  WARN: cannot write {config_path}: {exc}", file=sys.stderr)
    sys.exit(0)

print(f"  Pre-trusted {len(entries)} hook command(s) by hash -> {config_path}")
print("  (best-effort; if Codex still flags a hook, run a one-time `/hooks` review)")
PY

printf '%s\n' ""
printf '%s\n' "Done. Verify firing with the KTD-10 smoke test:"
printf '%s\n' "  1. cd into a Codex-trusted repo"
printf '%s\n' "  2. codex exec \"run the shell command: echo hi\"  # triggers a tool -> PostToolUse"
printf '%s\n' "  3. Confirm the reflector ran (set CODEX_REFLECTOR_DEBUG=1 for stderr diagnostics)."
printf '%s\n' "If a hook is skipped as untrusted, complete a one-time \`/hooks\` review in Codex."
