#!/bin/sh
set -eu

# install-antigravity.sh — install codex-reflector's Antigravity (agy) native
# JSON hooks, idempotently, and flip the `enable_json_hooks` gate that Antigravity
# requires before it fires JSON hooks at all.
#
# FIRING GATES (KTD-10 — Antigravity firing is INFERRED, not source-confirmed):
#   (a) hooks must actually fire under `agy -p` once enable_json_hooks is set;
#   (b) a Stop result delivered as decision:"continue"+reason must be re-injected
#       by Antigravity as actionable feedback (UNCONFIRMED). If (b) fails, the
#       reflector degrades to ADVISORY-ONLY on agy: the FAIL is still recorded to
#       /tmp fail-state and shown as a Stop systemMessage, but the agent is not
#       steered. Nothing here can verify (b) offline — confirm it live.
#   (c) PreToolUse deny support is UNVERIFIED, so NO pre-edit block hook is
#       installed (the reflector would only surface an advisory message anyway).
#
# WHY REFLECTOR_HOST=antigravity is pinned in every hook command (load-bearing):
#   The reflector namespaces non-default hosts' /tmp fail-state file as
#   codex-reflector-fails-antigravity-{session_id}.json (B5). A FAIL written at
#   PostToolUse must be READ at Stop under the SAME namespace. Antigravity's Stop
#   payload may carry no workspacePaths, so host inference would fall back to
#   "claude" and read the WRONG (bare) file, silently losing the FAIL. Pinning
#   REFLECTOR_HOST=antigravity (env wins in resolve_host) guarantees write==read.

usage() {
  printf '%s\n' "Usage: $0 [--force] [--settings-path PATH] [--hooks-path PATH]"
  printf '%s\n' ""
  printf '%s\n' "Installs codex-reflector Antigravity (agy) JSON hooks and enables"
  printf '%s\n' "the 'enable_json_hooks' setting that gates them."
  printf '%s\n' ""
  printf '%s\n' "Defaults:"
  printf '%s\n' "  settings: \$AGY_SETTINGS or ~/.gemini/antigravity-cli/settings.json"
  printf '%s\n' "  hooks:    \$AGY_HOOKS    or <settings-dir>/hooks.json"
  printf '%s\n' ""
  printf '%s\n' "  --force   replace an existing hooks.json instead of merging."
}

force=0
settings_path=""
hooks_path=""

while [ "$#" -gt 0 ]; do
  case "$1" in
    --force)
      force=1
      shift
      ;;
    --settings-path)
      if [ "$#" -lt 2 ]; then
        printf '%s\n' "--settings-path requires an argument." >&2
        exit 2
      fi
      settings_path=$2
      shift 2
      ;;
    --hooks-path)
      if [ "$#" -lt 2 ]; then
        printf '%s\n' "--hooks-path requires an argument." >&2
        exit 2
      fi
      hooks_path=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf '%s\n' "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

script_dir=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd -P)
plugin_root=$(dirname -- "$script_dir")
reflector_script="${plugin_root}/scripts/codex-reflector.py"

if [ ! -f "$reflector_script" ]; then
  printf '%s\n' "Cannot find codex-reflector.py at: $reflector_script" >&2
  exit 1
fi

# Resolve settings + hooks paths (flag > env > default).
if [ -z "$settings_path" ]; then
  settings_path=${AGY_SETTINGS:-"${HOME}/.gemini/antigravity-cli/settings.json"}
fi
settings_dir=$(dirname -- "$settings_path")
if [ -z "$hooks_path" ]; then
  hooks_path=${AGY_HOOKS:-"${settings_dir}/hooks.json"}
fi

hooks_dir=$(dirname -- "$hooks_path")
mkdir -p "$settings_dir" "$hooks_dir"

# Generate a WRAPPER that exports REFLECTOR_HOST=antigravity then execs the
# reflector (mirrors install-codex.sh). Env-setting lives in the wrapper, NOT as
# an inline `VAR=val cmd` prefix in the hook command, so host-pinning does not
# depend on agy shell-interpreting the command string — `sh <wrapper>` is a plain
# two-arg exec. REFLECTOR_HOST=antigravity is load-bearing for B5 (see note above).
wrapper_path="${hooks_dir}/antigravity-reflector-hook.sh"
cat > "$wrapper_path" <<WRAP
#!/bin/sh
# Auto-generated by install-antigravity.sh. Sets the Antigravity host then runs
# the reflector. REFLECTOR_HOST=antigravity pins the host so the namespaced /tmp
# fail-state file written at PostToolUse is read at Stop under the same namespace.
export REFLECTOR_HOST=antigravity
exec python3 "${reflector_script}" "\$@"
WRAP
chmod +x "$wrapper_path"
printf '%s\n' "Wrote hook wrapper: $wrapper_path"

# The command Antigravity runs for each event (absolute wrapper path; env-setting
# is inside the wrapper, robust to non-shell-interpreting hosts).
hook_command="sh \"${wrapper_path}\""

tmp_hooks=$(mktemp)
tmp_merged=$(mktemp)
tmp_settings=$(mktemp)
trap 'rm -f "$tmp_hooks" "$tmp_merged" "$tmp_settings"' EXIT INT HUP TERM

# --- Build the desired hooks bundle (absolute path, REFLECTOR_HOST pinned). ---
python3 - "$hook_command" > "$tmp_hooks" <<'PY'
import json
import sys

command = sys.argv[1]
bundle = {
    "description": (
        "codex-reflector Antigravity JSON hooks (gated by enable_json_hooks). "
        "REFLECTOR_HOST=antigravity pins the host so the namespaced /tmp "
        "fail-state file is written at PostToolUse and read at Stop under the "
        "same namespace. PostToolUse cannot inject on agy; Stop is the "
        "surfacing point (decision:continue+reason)."
    ),
    "hooks": {
        "PostToolUse": [
            {"hooks": [{"type": "command", "command": command, "timeout": 240}]}
        ],
        "PostToolUseFailure": [
            {"hooks": [{"type": "command", "command": command, "timeout": 120}]}
        ],
        "Stop": [
            {"hooks": [{"type": "command", "command": command, "timeout": 240}]}
        ],
        "PreCompact": [
            {"hooks": [{"type": "command", "command": command, "timeout": 240}]}
        ],
    },
}
print(json.dumps(bundle, indent=2))
PY

# --- Install / merge the hooks bundle (idempotent). ---
if [ -f "$hooks_path" ] && [ "$force" -ne 1 ]; then
  if command -v jq >/dev/null 2>&1; then
    # Idempotent merge: drop any prior codex-reflector entry for each event
    # (matched by the pinned command), then append ours. Re-running converges.
    jq --arg cmd "$hook_command" -s '
      def without_ours($command):
        map(
          if has("hooks") then
            . + {hooks: (.hooks | map(select((.command // "") != $command)))}
          else
            .
          end
        )
        | map(select((has("hooks") | not) or ((.hooks // []) | length > 0)));

      .[0] as $existing
      | .[1] as $ours
      | (($existing.hooks // {}) + ($ours.hooks // {}) | keys_unsorted | unique) as $keys
      | $existing + {
          hooks: reduce $keys[] as $key ({};
            .[$key] = (
              (($existing.hooks[$key] // []) | without_ours($cmd))
              + ($ours.hooks[$key] // [])
            )
          )
        }
    ' "$hooks_path" "$tmp_hooks" > "$tmp_merged"
    mv "$tmp_merged" "$hooks_path"
    printf '%s\n' "Merged codex-reflector hooks into $hooks_path"
  else
    printf '%s\n' "Refusing to overwrite existing $hooks_path because jq is unavailable." >&2
    printf '%s\n' "Install jq to merge automatically, or rerun with --force to replace." >&2
    exit 1
  fi
else
  mv "$tmp_hooks" "$hooks_path"
  printf '%s\n' "Installed codex-reflector hooks to $hooks_path"
fi

# --- Flip the enable_json_hooks gate in settings.json (idempotent). ---
# Antigravity does NOT fire JSON hooks unless this user setting is enabled.
# Exit 3 from the helper means the existing settings.json is malformed; we back
# it up and refuse to discard it silently (unless --force). Other JSON keys the
# user set are PRESERVED — we only add enable_json_hooks.
settings_status=0
python3 - "$settings_path" > "$tmp_settings" <<'PY' || settings_status=$?
import json
import os
import sys

path = sys.argv[1]
settings = {}
if os.path.exists(path):
    try:
        with open(path) as f:
            loaded = json.load(f)
    except (json.JSONDecodeError, ValueError, OSError):
        sys.exit(3)  # malformed -> caller decides (back up, don't discard)
    if not isinstance(loaded, dict):
        sys.exit(3)
    settings = loaded

settings["enable_json_hooks"] = True
print(json.dumps(settings, indent=2))
PY

if [ "$settings_status" -eq 3 ]; then
  if [ "$force" -ne 1 ]; then
    printf '%s\n' "Existing $settings_path is not valid JSON object." >&2
    printf '%s\n' "Refusing to discard it. Fix it, or rerun with --force to back it up and replace." >&2
    exit 1
  fi
  backup="${settings_path}.bak.$(date +%Y%m%d%H%M%S)"
  cp -- "$settings_path" "$backup"
  printf '%s\n' "Backed up malformed settings to $backup" >&2
  printf '%s\n' '{
  "enable_json_hooks": true
}' > "$tmp_settings"
elif [ "$settings_status" -ne 0 ]; then
  printf '%s\n' "Failed to read/update $settings_path (exit $settings_status)." >&2
  exit 1
fi

mv "$tmp_settings" "$settings_path"
printf '%s\n' "Enabled enable_json_hooks in $settings_path"

printf '%s\n' ""
printf '%s\n' "Done. FIRING GATES to confirm LIVE (KTD-10):"
printf '%s\n' "  (a) hooks fire under 'agy -p' with enable_json_hooks set;"
printf '%s\n' "  (b) Stop decision:\"continue\"+reason re-injects reason as feedback"
printf '%s\n' "      (UNCONFIRMED -> advisory-only fallback if it does not);"
printf '%s\n' "  (c) PreToolUse deny is UNVERIFIED -> no pre-edit block installed."
